#!/bin/ash
run_hook() {
  if [ "\${oroot}" ]; then
     fsck_root() {
       echo &>/dev/null
     }
     if [ ! -b "/dev/zram0" ]; then
        modprobe zram num_devices=\$((\$(nproc)+2))
     fi
     echo "#!/bin/bash
           mkdir /run/oroot"

  # generate part of the overlay_flush script
  genOverlayFlush() {
    read b
    # sort the kernel cmdline parameters alphabetically
    for a in $(sort <(for c in $b; do echo $c; done)); do
      case "$a" in
	cryptdevice*UUID*)
	  crypt_root="${a#cryptdevice=UUID=}"
	  cat <<EOF >> oroot
	     if [ \"\$oroot\" = \"live\" ]; then
		cryptsetup open \"/dev/disk/by-uuid/${crypt_root%:*}\" \"${crypt_root#*:}\" \\
EOF
	  ;;
	cryptdevice)
	  crypt_root="${a#cryptdevice=}"
	  cat <<EOF >> oroot
	     if [ \"\$oroot\" = \"live\" ]; then
		cryptsetup open \"${crypt_root%:*}\" \"${crypt_root#*:}\" \\
EOF
	  ;;
	cryptkey*UUID)
	  cryptkey_root="${a#cryptkey=UUID=}"
	  cat <<EOF >> oroot
		  --key-file \\\$(mkdir \"/run/oroot-key\"; mount -U \"${cryptkey_root%%:*}\" \"/run/oroot-key\"; echo \"/run/oroot${cryptkey_root##*:}\")
	   fi
EOF
	  unset cryptkey_root
	  ;;
	cryptkey*)
	  cryptkey_root="${a#cryptkey=}"
	  cat <<EOF >> oroot
		  --key-file \\\$(mkdir \"/run/oroot-key\"; mount \"${cryptkey_root%%:*}\" \"/run/oroot-key\"; echo \"/run/oroot${cryptkey_root##*:}\")
EOF
	  unset cryptkey_root
	  ;;
	root*UUID*)
	  # need to newline before fi for cryptsetup to break \
        if [ "$crypt_root" ]; then
        cat <<EOF >> oroot
        
           fi
           mount -U \"${a#root=UUID=}\" \\
EOF
          else
        cat <<EOF >> oroot
           mount -U \"${a#root=UUID=}\" \\
EOF
        fi
        ;;
      root*)
        if [ "$crypt_root" ]; then
        cat <<EOF >> oroot
        
           fi
           mount --source \"${a#root=}\" \\
EOF
         else
        cat <<EOF >> oroot        
           mount --source \"${a#root=}\" \\
EOF
        fi
        ;;
    esac
  done
  unset b
}

# interpret kernel cmdline options and pass to above loop
genOverlayFlush </proc/cmdline
