#!/bin/ash
#vim: set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

run_hook() {
  #reads a config file line by line
  #config format is 'key=value' repeated on any number of lines
  IFS='='
  while read -r k v
  do
    export "oroot_settings_${k}=${v}"
  done </etc/oroot.conf
  IFS=

  
  if [ "\${oroot}" ]; then
     fsck_root() {
       echo &>/dev/null
     }
     if [ ! -b "/dev/zram0" ]; then
        modprobe zram num_devices=\$((\$(nproc)+2))
     fi
     echo "#!/bin/bash
           mkdir /run/oroot"

  # generate part of the overlay_flush script
  genOverlayFlush() {
    # sort the kernel cmdline parameters alphabetically
    for a in $(sort <(for c in $(cat /proc/cmdline); do echo $c; done)); do
      case "$a" in
	cryptdevice*UUID*)
	  crypt_root="${a#cryptdevice=UUID=}"
	  cat <<EOF
	     if [ \"\$oroot\" = \"live\" ]; then
		cryptsetup open \"/dev/disk/by-uuid/${crypt_root%:*}\" \"${crypt_root#*:}\" \\
EOF
	  ;;
	cryptdevice)
	  crypt_root="${a#cryptdevice=}"
	  cat <<EOF
	     if [ \"\$oroot\" = \"live\" ]; then
		cryptsetup open \"${crypt_root%:*}\" \"${crypt_root#*:}\" \\
EOF
	  ;;
	cryptkey*UUID)
	  cryptkey_root="${a#cryptkey=UUID=}"
	  cat <<EOF
		  --key-file \\\$(mkdir \"/run/oroot-key\"; mount -U \"${cryptkey_root%%:*}\" \"/run/oroot-key\"; echo \"/run/oroot${cryptkey_root##*:}\")
	   fi
EOF
	  unset cryptkey_root
	  ;;
	cryptkey*)
	  cryptkey_root="${a#cryptkey=}"
	  cat <<EOF
		  --key-file \\\$(mkdir \"/run/oroot-key\"; mount \"${cryptkey_root%%:*}\" \"/run/oroot-key\"; echo \"/run/oroot${cryptkey_root##*:}\")
EOF
	  unset cryptkey_root
	  ;;
	root*UUID*)
	  # need to newline before fi for cryptsetup to break \
        if [ "$crypt_root" ]; then
        cat <<EOF
        
           fi
           mount -U \"${a#root=UUID=}\" \\
EOF
          else
        cat <<EOF
           mount -U \"${a#root=UUID=}\" \\
EOF
        fi
        ;;
      root*)
        if [ "$crypt_root" ]; then
        cat <<EOF
        
           fi
           mount --source \"${a#root=}\" \\
EOF
         else
        cat <<EOF
           mount --source \"${a#root=}\" \\
EOF
        fi
        ;;
    esac
  done
}

# interpret kernel cmdline options and pass to above loop
$(genOverlayFlush)

#mount root with options parsed from fstab
mount -o $(awk '{if ($2 == "/") {print $4}}' /etc/fstab) "/run/oroot"


if [ "$oroot_settings_btrfs" = 'true' ]; then
   if [ "$oroot" = "live" ]; then
      btrfs subvolume snapshot / /oroot-snap
      cd /oroot-snap
    else
      cd /
   fi
 else
   cd /
fi

